version: "3.9"
services:
  scraper:
    image: docker.io/raelix/amazon-bot:latest
    environment:
      - IS_TEST=False
      - USE_TOR=False
      - PERCENTAGE=70
      - LIMIT_PRICE=${LIMIT_PRICE}
      - AMAZON_EMAIL=${AMAZON_EMAIL}
      - AMAZON_PASSWORD=${AMAZON_PASSWORD}
    volumes:
      - ./../src/data/urls.txt:/usr/src/app/data/urls.txt
