version: "3.9"
services:
  scraper:
    image: docker.io/raelix/amazon-bot:latest
    environment:
      # - POOL_SIZE=20
      - WAIT_RANDOM=false
      - SAMPLES=10
      - PERCENTAGE=60
      - REQUEST_TIMEOUT=10
      - WAIT_BEFORE_LOGIN=1800
      - STANDALONE_PROXY=true
      - PROXY_TYPE=tor
      - IS_TEST=False
      - IS_CONTAINERIZED=true
      - PORTAL=https://www.amazon.it
      - AMAZON_EMAIL=${AMAZON_EMAIL}
      - AMAZON_PASSWORD=${AMAZON_PASSWORD}
    volumes:
      - ./../src/urls.txt:/usr/src/app/urls.txt
